spring:
  profiles:
    active: 
      - dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/clouddb01
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: wei123
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: cn.wxb.spring.entity
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml

eureka:
  client:
    service-url:
      #defaultZone:http://localhost:7001/eureka
      defaultZone:  http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true

info:
  app.name: cloud_parent
  company.name: www.wxb.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}


---
spring:
  profiles: test
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/clouddb02
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: wei123
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: cn.wxb.spring.entity
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml

eureka:
  client:
    service-url:
      #defaultZone:http://localhost:7001/eureka
      defaultZone:  http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true

info:
  app.name: cloud_parent
  company.name: www.wxb.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
